### PR TITLE
fixed typo, language

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Myzel394** [comment]
Thank you, we can merge this once the translations are done

**Comment by lucasmz-dev** [comment]
sorry this PR is confusing me, I was planning on translating this to PT-BR (https://codeberg.org/lucasmz/translation-suggestions/issues/28) and I'm a bit confused on where PT is being worked on? Who's doing it?

**Comment by lucasmz-dev** [comment]
Oh. I'm not that sure I'll do it just because the format used here is not the standard Android one and I'm a bit lost to be honest, and there's a LOT of text, and it doesn't look like they'd be that much from the current app.

**Comment by lucasmz-dev** [comment]
sure ig, anyway the size is the annoying thing, and I'm not gonna use computer translation, that misses the point IMO, anyhow I'll look into it. Just more used to messing with files directly on /app/

having a weblate instance would help but yeah anyway

**Pull request closed without merging**
